### ISSUE TITLE
Environmental data

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#10]
So I looked through my hard drive at the temperature.gz files, and there aren't any .prj, just .shp, .shx, and .dbf. When I do `proj4string(temp)` it returns an NA value, so trying to execute `spTransform` on it doesn't work. I'm not even sure what is inside the chlorophyll data because when I unzip it the file is listed without a file type and neither R nor any program on my computer will open it

**Comment by EmmalineSheahan** [comment]
I plotted the temperature data versus a map of the world with a longlat CRS and they matched up, and the raster worked when I did this

```
proj4string(temp) <- "+proj=longlat +datum=WGS84"
temp <- spTransform(temp, CRS("+proj=cea +units=km"))
names(temp)
head(temp$SURFACE)
temp_raster <- rasterize(temp, oceans_raster, 'd5500M')
res(temp_raster) <- 110
plot(temp_raster)
```
but looking at the data itself it seems kind of off, the values don't look like something you'd get in degrees C, even though that's what NOAA says it should be, so I'm going to download the CSV version and look at it in a text editor

**Comment by EmmalineSheahan** [comment]
So everything looks normal enough in excel, but I'm getting a lot of errors trying to do really anything with the temperature data set. In my local R, if I try to run

`temp_raster <- rasterize(temp, oceans_raster, 'd10M')`

I get an error that says it can't allocate a vector of size 9.1 GB. If I try the same code in the server, it tells me values must be either numeric, integer, or logical, even though the values are most certainly numeric. If I check what type the values are however, it says they're double, and I'm really not sure what that means. The rasterize code works perfectly well on both my local program and the server when I use the surface data as the field, however, strangely, but it won't work for other depths. Other papers I looked through relating ocean species richness to temperature varied in what temperature they used, but it seemed like the consensus, and what makes most sense to me, is to use the mean temperature at the depth where most species occur. Unfortunately we do not have depth information for each species, but just doing outside research it looks like the deepest a shark has ever been known to dive is 3700 meters, and that's the portuguese dogfish shark. It's average depth at which its found is between 396 and 1981 meters. I feel as though it wouldn't really be accurate to only use the surface data considering the fact that there's an entire clade of sharks, sleeper sharks primarily, as well as quite a few other species, like the goblin shark and the frill shark, who don't interact with the euphotic zone at all, even though likely the majority of the other families do.  So then I wondered if it would potentially make sense to use the average temperature across all depths wherein sharks are known to occur, from the surface down to 3700 meters, and I attempted to create another field in the temp data frame for that result using this code 

`temp$depth_mean <- rowMeans(temp[ ,1:85], na.rm = TRUE)`

but that returns an error saying x must have at least 2 dimensions. But then when I do

`dim(temp[,1:85])`

it does return 2 dimensions, 39969 values in 85 columns, so I'm not entirely sure what's wrong

**Comment by dmcglinn** [comment]
Based on your description it does sound like the data is in geographic coordinates (i.e., lat long). Merging #8 solves these issues.

**Comment by EmmalineSheahan** [comment]
As far as the chlorophyll data goes, I'm having trouble getting it into a readable format. NOAA has a program that will convert the downloaded .gz file into .csv (because just unzipping it leaves it in a format that I can't even decipher) but each time I attempt to run it internet explorer tells me it encountered a problem and shuts the program down (which is really weird considering the fact that I'm using chrome). It won't run at all on the library computers. here's the instruction page they give: [link](https://www.nodc.noaa.gov/OC5/TUTORIAL/csvfromwod_instructions.html)

**Comment by EmmalineSheahan** [comment]
So I found chlorophyll data from NASA: [here](https://neo.sci.gsfc.nasa.gov/view.php?datasetId=MY1DMM_CHLORA)

And I can download it and read it in directly as a raster, which should make things easier, the only issue is that, in the original form, they have everywhere they didn't collect data colored in black (land and ice sheets). but for some reason when I reproject the raster, it doesn't register those values as NA, but as the max value, 250, so the land and ice sheets end up colored in in green (the original values aren't listed as NA either, but as 99999.0, and changing those to NA doesn't solve the problem). I have no problem masking the continents by making another raster layer out of the oceans polygon, but that doesn't mask the ice sheets where NASA claims there shouldn't be data. I guess I could try cropping them out, but I don't know how accurate that would be. Any ideas?

**Comment by dmcglinn** [comment]
Cool on new dataset! It looks like `raster::NAvalue`  should do the trick. See the help file for this function.

**Comment by EmmalineSheahan** [comment]
`NAvalue(chloro) <- 255` didn't work, but `values(chloro_ras)[values(chloro_ras) == 255] <- NA` did
