### ISSUE TITLE
bathymetry file conversion steps

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/shark-ray-div#16]
The data can be downloaded here: 

http://topex.ucsd.edu/WWW_html/mar_topo.html

precisely here is the version of the data we need for our purposes: 

ftp://topex.ucsd.edu/pub/global_topo_1min/topo_18.1.img

The problem is that R's functions `raster::raster` and `rgdal::readGDAL` cannot import this specific file although in general they should work for .img files. The solution was to use a 3rd party program called `GMT` downloaded here: http://gmt.soest.hawaii.edu/projects/gmt/wiki/Download 

The idea is to use `GMT` to convert it to a format that is easier to import into R. I used the function `img2grd` based on the instructions provided here:

https://grasswiki.osgeo.org/wiki/Marine_Science

`img2grd topo_18.1.img -T1 -S1 -V -R0/360/-80.738/80.738 -m1 -D -Gtopo_all.grd`

But I still received an error when trying to import it to R so I then used an additional `GMT` function called `grd2xyz` which outputs a simple matrix of x, y, and z values. This R can definitely import!! 

`gmt grd2xyz topo_all.grd > topo_all.xyz`

When this is finished getting generate then I should be able to use the function `raster::rasterFromXYZ` to convert the object to a raster object. We will still have to be careful about the projection information which will have to be extracted from this file: 

ftp://topex.ucsd.edu/pub/global_topo_1min/arcinfo_2min.html

Note, my understanding is that all of this trouble is due to the fact that the authors shared the output from a priority software bundle (ArcGIS) rather than providing it in an open source format.

**Comment by EmmalineSheahan** [comment]
So I input this code into the GMT command

`img2grd topo_18.1.img -T1 -S1 -V -R0/360/-80.738/80.738 -m1 -D -Gtopo_all.grd`

and I got these errors:

```
error for input file: no such file <topo_18.1.img>
warning -m<inc> is deprecated; use -I<inc> instead
syntax error: must specify input imgfile name
```
I'm not super familiar with this kind of code but I'm guessing the problem has to do with the topo_18.1.img file path? Right now it's in my downloads with the exact same name

**Comment by dmcglinn** [comment]
I just put the file `topo_all.xyz` in your home directory. See if you can get this shaped up for use. Let me know if you have trouble.

**Comment by dmcglinn** [comment]
Randy Warren suggested this as a good potential source: 
https://www.ngdc.noaa.gov/mgg/bathymetry/relief.html
Which links to this source: 
https://www.ngdc.noaa.gov/mgg/global/global.html

which has exactly what we need. Specifically I had no trouble reading in the following file in R: 
https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/cell_registered/netcdf/ETOPO1_Ice_c_gmt4.grd.gz

```r
library(raster)
library(ncdf4)
topo = raster('./etopo/ETOPO1_Ice_c_gmt4.grd')
proj4string(topo) = CRS("+proj=longlat +datum=WGS84")
topo
plot(topo)
```

**Comment by dmcglinn** [comment]
Emmaline I'll put this file in your server working directory

**Comment by dmcglinn** [comment]
Here is also a good link that describes the difference between grid-registered and cell-registered raster layers: 
https://www.ngdc.noaa.gov/mgg/global/gridregistration.html
I went with cell-registered because that seems like the most similar to the other kinds of layers we've been working with.

**Comment by dmcglinn** [comment]
Oh and rather than converting it to a polygon and then using `spTransfrom` to project it to lambert equal area just use the function `projectRaster` to reproject the rater directly.

**Comment by EmmalineSheahan** [comment]
Awesome! I'll get on this tomorrow and hopefully I should have bathymetry and the related correlations plotted by then
