### ISSUE TITLE
Mean Root Distance

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#17]
I'm trying to rasterize the bathymetry data right now in the server, it's just taking a really long time because the data file is so huge. In the mean time I've been trying to set up the code for mean root distance and I'm a little confused about this line:

```
output = c()
for (i in lat) {
  species = subset(sebastes, min_latitude <= i & max_latitude >= i, select='X')

```
because species shows up here:

```
MRD.ini <- merge(species, tips.to.root, by.x="X", by.y="spp.name",sort = FALSE)
  MRD <- mean(MRD.ini$root.dist)
```

It looks like the first line is getting all the latitude values for each tip, and I don't quite understand why that goes into the calculation of MRD as opposed to something like a site by species matrix. Would our site by species matrix work in place of that? Otherwise I think I'd somehow have to calculate how many species there are in each pixel to every corresponding bathymetry value

**Comment by dmcglinn** [comment]
Hey @EmmalineSheahan I uploaded the code to the github repo so we can reference it more easily. The first line in question is here: https://github.com/mcglinnlab/shark-ray-div/blob/master/sebastes_ex/sebastes.r#L40

Essentially what they are doing is making just a string of species names that fall within a given range of latitudes. If you take a look at the object `sebastes` you will see that for each species they have a min and max latitude that essentially sets the species range. The column `X` is just the name of the column that contains the species names. 

The species names are then merged with the object `tips.to.root` which is each species name and its distance to the root of the phylogenetic tree. This merge essentially just subsets `tips.to.root` to only those species that occur in that particular latitude bin. The mean of those species root distances can then be calculated. A site-by-species matrix as we are working with is more informative then the latitude ranges they have for the sebastes but it does make things more complicated. From our perspective we will want to compute for every map pixel what MRD is. Essentially go to each pixel generate a species list and then compute the mean of the root distances. Then we'll regress those MRD values against the pixel depth or latitude or NPP or whatever variable we would like. Does that make sense?
