### ISSUE TITLE
beta statistic instability

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/shark-ray-div#19]
Hey @EmmalineSheahan I played around with the beta statistic estimator, and it is definitely sensitive to smaller trees. Here are some quick simulation results
```r
library(apTreeshape)
# simulate yule tree which should have beta of 0
b100 = sapply(rtreeshape(n=50, tip.number=100, model="yule"),  maxlik.betasplit)
b10 = sapply(rtreeshape(n=50, tip.number=10, model="yule"),  maxlik.betasplit)
b5 = sapply(rtreeshape(n=50, tip.number=5, model="yule"),  maxlik.betasplit)

boxplot(unlist(b100), unlist(b10), unlist(b5), names = c('100sp', '50sp', '5sp'),
        ylab='beta')
```
here is the resulting boxplot

![plot_zoom_png](https://user-images.githubusercontent.com/1190381/32801469-29cff5ea-c94b-11e7-85ee-497d7d1b2cb8.png)

**Comment by EmmalineSheahan** [comment]
Yeah that looks pretty significantly varied, should I run the beta code again but this time set a minimum number of taxa the tree has to have in order to get a value, or should we just mention in the paper that beta is heavily influenced by how many species are in the tree? I think the greatest number of species in any cell at the finest resolution is 69.

**Comment by dmcglinn** [comment]
I think some kind of minimum richness is likely going to be needed - it also suggests that maybe our grid resolution doesn't really make sense for the beta-statistic - maybe we should only calculate it once at the bio-geographic province level. 

If we want to look more closely at the spatial patterns then I propose that we also calculate beta's confidence interval for each cell and then use that as an inverse weighting system if beta is included in any regressions - on a may the weighting system could be illustrated by how grey the cell is.
