### ISSUE TITLE
richness around South Africa

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#20]
So it's definitely not the mask, because I ran it without it and all of the richness areas are the same between the two:
[species_richness_maps.pdf](https://github.com/mcglinnlab/shark-ray-div/files/1620887/species_richness_maps.pdf)
[species_richness_maps_trial.pdf](https://github.com/mcglinnlab/shark-ray-div/files/1620888/species_richness_maps_trial.pdf)

The thing I did notice however is that south africa is a hotspot for all of the resolutions except the largest, which is incidentally the one we reported on in the paper. That makes me think a lot of the richness there is localized to an extent just so that it becomes diluted at the 1100 resolution. If Gavin thinks it would be more accurate, we could report on a smaller resolution like the 770 one, or I could add in resolutions between the two and see how those look

**Comment by dmcglinn** [comment]
Thanks for looking into this! Hmm, I'm not sure what the best answer here is but it does seem unsatisfying that the 1100 resolution is missing those hotspots. How do you feel about including richness in the partial pixels that overlap with the land? We could possibly include pixel area as a covariate to factor out when running regressions.
