### ISSUE TITLE
fixing the community matrix

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#23]
So now that the rasterization is coded differently, I'm having a bit of trouble with the community matrix. The original code is this:

```
i <- 1
mat_list <- vector("list", length = 9)
for (j in 1:7) {
    mat_list[[j]] = matrix(NA, ncol = sum(test_species), 
                            nrow=length(raster_res_list[[j]][[i]]@data@values))
    colnames(mat_list[[j]]) = species_names_poly[test_species]
    icol = 1
    for (i in which(test_species)) {
         mat_list[[j]][ , icol] = raster_res_list[[j]][[i]]@data@values
         icol = icol + 1
    }
    mat_list[[j]] = ifelse(is.na(mat_list[[j]]), 0, mat_list[[j]])
}
```

Seeing as there is no longer a raster_res_list, I'm considering replacing it with the sp_raster_files, seeing as that's the same as what we were getting by calling the ith element (raster data for a specific species) from the jth element of the raster_res_list. The issue though is when I run this in order to try to call the sp_raster_files since we used writeraster to put it under that file path:

`sp_raster_files <- load('./data/raster/sp/')`

I get this error:

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file './data/raster/sp/', probable reason 'Permission denied'

**Comment by EmmalineSheahan** [comment]
I attempted to bypass the loading issue by just running the entire for loop, except now checking the class of sp_raster_files (or any element of it) it returns character, which won't work in the community matrix code. I'm somewhat confused because all of the elements of sp_raster_files end in .grd; shouldn't they be the rasters of each individual species?

**Comment by EmmalineSheahan** [comment]
So I replaced the raster_res_list with the sp_res_stack, and the community matrix code ran without any errors, but when I attempted to apply it to MRD I hit an error with

`mat_list[[i]][j,]`

saying that the subscript was out of bounds. I'm not entirely sure what the issue is, seeing as it should just be pulling out the rows of the matrix and that code works with a test matrix I tried out

**Comment by dmcglinn** [comment]
Hey @EmmalineSheahan good job finding a work around. Can you push your code so I can more easily see where the problem is occurring?

**Comment by EmmalineSheahan** [comment]
I think I did push that commit, do i need to make a pull request?

**Comment by EmmalineSheahan** [comment]
I figured it out; for some reason @data@values doesn't work anymore, so I just switched it out for the extract function. Here's the new code:

```
i <- 1
mat_list <- vector("list", length = length(sp_res_stack))
for (j in 1:6) {
    mat_list[[j]] = matrix(NA, ncol = sum(test_species), 
                            nrow=length(sp_res_stack[[j]][[i]]))
    colnames(mat_list[[j]]) = species_names_poly[test_species]
    icol = 1
    for (i in which(test_species)) {
         mat_list[[j]][ , icol] = extract(sp_res_stack[[j]][[i]], 
                                          1:nrow(mat_list[[j]]))
         icol = icol + 1
    }
    mat_list[[j]] = ifelse(is.na(mat_list[[j]]), 0, mat_list[[j]])
}
```
I've already successfully gotten it to work on the mrd rasters and I'm running the rest of the phylogenetic data now; I'll push a commit when I'm done and put all of the new figures in the dropbox
