### ISSUE TITLE
projectRaster error

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#34]
Under the help view for the projectRaster function, it says it should work solely with the "from" and "crs" arguments, but when I try this code:

```
for(i in 1:6) {
  for_indo[[i]] <- projectRaster(from = species_richness[[i]], 
                                 crs = "+proj=cea +lat_0=0 +lon_0=125 +units=km")
}
```
I get this error:

Error in if (maxy == miny) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In rgdal::rawTransform(projfrom, projto, nrow(xy), xy[, 1], xy[,  :
  53 projected point(s) not finite

**Comment by dmcglinn** [comment]
This first hit on google suggests that the `not finite` warning may not be of much concern: 

https://gis.stackexchange.com/questions/204533/re-projecting-raster-in-r-gives-warning-that-projected-points-not-finite

I'm still googling for info on the other `maxy==miny` error

**Comment by dmcglinn** [comment]
Here's a related thread that helps to understand what happened. It appears that cropping the globe a bit may resolve this problem.  

https://gis.stackexchange.com/questions/220589/error-using-projectraster-in-r-error-in-if-maxy-miny-missing-value-whe

**Comment by EmmalineSheahan** [comment]
So I tried this:

```
for(i in 1:6) {
  extent(for_indo[[i]]) <- c(xmin= xmin(species_richness[[i]]), 
                                   xmax = xmax(species_richness[[i]]), 
                                   ymin = 0.99*ymin(species_richness[[i]]),
                                   ymax = 0.99*ymax(species_richness[[i]]))
  for_indo[[i]] <- projectRaster(from = for_indo[[i]], 
                                crs = "+proj=cea +lat_0=0 +lon_0=125 +units=km")
}
```

and for some reason it works for the first three projections, but stops working at the fourth. Looking at the original extent of species richness, the first three are exactly the same, the fourth is different, and then the fifth and sixth are different but the same as each other. I'm not sure why that would impact the code I have written though.

**Comment by EmmalineSheahan** [comment]
So it apparently has to do with how much it's cropped by; the threshold for it to work without getting an error is 0.82

```
for(i in 1:6) {
  extent(for_indo[[i]]) <- c(xmin= xmin(species_richness[[i]]), 
                                   xmax = xmax(species_richness[[i]]), 
                                   ymin = 0.82*ymin(species_richness[[i]]),
                                   ymax = 0.82*ymax(species_richness[[i]]))
  for_indo[[i]] <- projectRaster(from = for_indo[[i]], 
                                crs = "+proj=cea +lat_0=0 +lon_0=125 +units=km")
}
```
the issue though now is I need to similarly crop and reproject the res stack for it, but the same exact code will not work, which is troubling, since everything needs to have the same extent later on. Additionally, trying to get the continents to match up when plotted is becoming tricky. I'm beginning to think everything may be cleaner/simpler if I instead drop the one portion of the realm which is stretching the map, unless there's a different way to change the projection of the raster or recenter it without using projectRaster?

**Comment by EmmalineSheahan** [comment]
If we drop the two little regions stretching the map, here's the code that does it:

```
drop1 <- grep("Tonga Islands", regions$ECOREGION)
drop1 <- regions[drop1,]
drop2 <- grep("Fiji Islands", regions$ECOREGION)
drop2 <- regions[drop2,]
drop_indo <- rbind(drop1, drop2)
test <- gDifference(central_indopacific, drop_indo)
test <- spTransform(test, CRS("+proj=cea +units=km"))
```
here's what the whole indopacific looks like:

[indo.pdf](https://github.com/mcglinnlab/shark-ray-div/files/2234430/indo.pdf)

and here's what the cropped version looks like:

[cropped indo.pdf](https://github.com/mcglinnlab/shark-ray-div/files/2234431/cropped.indo.pdf)

**Comment by EmmalineSheahan** [comment]
I got it to work basically by rerasterizing the entire data set in the other projection, but now for some reason when I plot the continents on top of it it's distorted really badly by the projection:

[indopacific_richness.pdf](https://github.com/mcglinnlab/shark-ray-div/files/2243195/indopacific_richness.pdf)

**Comment by dmcglinn** [comment]
Hey emmy, I'm sorry for being out of touch on this issue. I'm better able to help now. Just to follow up on my previous suggestion did you try to use the function `crop` to simply crop out the furthermost eastern edge of the map and down to the western edge of the Indo region. Specifically I think you need to crop when it is in the native coordinate reference system (i.e., prior to converting to cea). If you've already tried this forgive me.

**Comment by EmmalineSheahan** [comment]
So I can't do that in the native reference system because it would cut out the two little ecoregions which are stretching the map and show up on the eastern side. I have code written that drops them from the analysis but I know we're trying to avoid that. I tried cropping species richness in that manner before attempting to use projectRaster with this code:

```
for(i in 1:6) {
  r <- extent(10000, xmax(species_richness[[i]]), 
              ymin(species_richness[[i]]), ymax(species_richness[[i]]))
  for_indo[[i]] <- crop(for_indo[[i]], r)
  for_indo[[i]] <- projectRaster(from = for_indo[[i]], 
                                crs = "+proj=cea +lat_0=0 +lon_0=125 +units=km")
}
```
but that didn't work because the issue is that it's too big vertically. I'm having an issue cropping everything vertically because it's incredibly arbitrary what projectraster will accept; ie, where an 82% crop works on each resolution of the richness rasters, it doesn't on the raster stack, so I would have to crop that even more which means the richness rasters and the stacks for each of their resolutions would be in different extents and would likely no longer function with eachother. Rerasterizing everything in the other projection worked,  but now the issue is I did that in the server because I didn't want to run something like that locally, and then I just downloaded the richness and raster stack files. For some reason I have absolutely no problem opening and working on the richness file locally, but trying to use this code on the stack:

```
# realm_crop function
# x = output list
# y = realm spatial object
realm_crop <- function(x, y) {
  temporary <- vector("list", length = 6)
  for (i in 1:6) {
    ras <- intersect(x[[i]], y)
    temporary[[i]] <- ras
  }
  return(temporary)
}

indopacific_stack <- realm_crop(for_indo_stack, central_indopacific)
```
gives me this error:

Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
 
 Show Traceback
 
 Rerun with Debug
 Error in file(fn, "rb") : cannot open the connection

**Comment by dmcglinn** [comment]
Thanks for the clarification. At this point I would suggest we try to find the simplist solution - if it is simply cropping out a small portion of the Indo region I would go with that option. Regarding your most recent question I'm not sure what is going on but it appears that one of the objects you are calling is not getting read from memory. Is one of the files you're working with here really large - usually R has all of its objects stored in RAM so this is not an issue but for large rasters it uses a temporary file system to read and write from during processing tasks. Also is there a reason you are using the function `intersect` instead of `crop`?

**Comment by EmmalineSheahan** [comment]
`intersect` basically crops a raster to just the region within the second argument, which is a spatial polygon in this case. Basically I was intersecting the richness raster with the spatial polygons for each region to get the richness of each region. Is there an advantage to using crop? It seems like according to the help function they seem to achieve the same thing; intersect was likely merely the first function I came across that would do what I wanted. Regarding the issue, I could just attempt to run everything in the server (including rerasterizing all of the data in the recentered projection) instead of trying to transfer things between the two, then we wouldn't lose any data by cropping out the two ecoregions. I'll try that now, and if that's to no avail I'll go the route of cropping

**Comment by EmmalineSheahan** [comment]
I ran everything in the server and it looks like it all worked out fine, the only issue though is that the continents get distorted pretty badly in the recentered projection. but all of the data looks to be intact and I was able to run psv and mrd. Beta for some reason is not cooperating with either but I should probably open a new issue for that
