### ISSUE TITLE
Updates for README.md

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/shark-ray-div#37]
just a few small todo list for the `README.md` file:

- [x] the zenodo data is polygon data not raster - update text accordingly
- [x] when referencing files in the directory be sure to include their path. For a file in the home directory it would be `./tree_stuff.R` for example. For a file in the scripts directory it would be `./scripts/Phylogenetic_metrics.R` for example. 
- [x] Wrap all file and R object names in back ticks "`" so that they are highlighted grey by markdown and given a different font
- [x] Your bulleted list is not properly formatted because you did not include four spaces in to start a new intent. I'm happy to help you fix this if you want
- [x] include link to temperature layer needed for paper analysis

**Comment by EmmalineSheahan** [comment]
I'm not quite sure what happened but now the entire bulleted list is highlighted grey and in the font which should just be for R files and Robjects

**Comment by dmcglinn** [comment]
let me take a crack real quick
