### ISSUE TITLE
For loop coding

### ISSUE THREAD

**Issue by EmmalineSheahan** [mcglinnlab/shark-ray-div#6]
So there's an issue with this code, but I'm really not sure what

```r
for (j in seq_along(res_list)) {
     for (i in seq_along(sp_files)) {
    # read in 
    temp_poly = readOGR(dsn = paste("./data/polygon/", sp_files[i], sep=''),
                        layer = "OGRGeoJSON")
    # convert projection to cea
    temp_poly = spTransform(temp_poly, CRS("+proj=cea +units=km"))
    # add field that will provide values when rasterized
    temp_poly@data$occur = 1
    # rasterize
    sp_raster[[i]] = rasterize(temp_poly, res_list[[j]], field = 'occur')
     }
  raster_res_list[[j]] = lapply(raster_res_list, function(x) sp_raster[j])
}
```
the raster_res_list that's created ends up having seven raster layers for each resolution instead of having one sp_raster list for each resolution, and when I try to plot the different resolutions from the list they come out looking like partial ranges. Using [[j]] in the last sp_raster didn't solve the problem. I also tried to make a for loop that would plot species richness at each resolution with this code, but it doesn't work, and I'm not sure if that's because of the code itself or because the raster_res_list doesn't look the way it should

```r
# creating a species richness layer for each resolution
species_richness_list <- vector("list", length = length(raster_res_list))
for (i in seq_along(raster_res_list)) {
    sp_raster_stack <- stack(raster_res_list[[i]])
    species_richness <- calc(sp_raster_stack, fun = sum, na.rm = T)
    plot(species_richness)
    plot(world, add = T)
    species_richness_list[[i]] <- lapply(species_richness_list, function(x) species_richness)
}
```

**Comment by EmmalineSheahan** [comment]
I just removed the [j] entirely from the last sp_raster and am running it again to see if that fixes it, because I just realized we don't want to be selecting elements from that list, we want the entire list

**Comment by dmcglinn** [comment]
As you try to troubleshoot this I would definitely do this for a subset of species and resolutions so it runs faster

**Comment by dmcglinn** [comment]
Can you explain in words what this line of code is doing the first for loop you provided above:
`raster_res_list[[j]] = lapply(raster_res_list, function(x) sp_raster[j])`

**Comment by dmcglinn** [comment]
Another trick to debugging these for loops if you can't spot the mistake with your eyes is to run each line one at a time (i.e., not as a for loop) just set the indices of the for loops manually.

**Comment by EmmalineSheahan** [comment]
I changed the last line to 

`raster_res_list[j] = lapply(raster_res_list, function(x) sp_raster)`

So this is saying each formerly null element of the raster_res_list is being filled with the sp_raster as sequenced along the res_list. I ran it with just the head of the species list and it seemed to work right this time, as did this for loop for plotting the different resolutions

```
# creating a species richness layer for each resolution
species_richness_list <- vector("list", length = length(raster_res_list))
for (i in seq_along(raster_res_list)) {
sp_raster_stack <- stack(raster_res_list[[i]])
species_richness <- calc(sp_raster_stack, fun = sum, na.rm = T)
plot(species_richness)
plot(world, add = T)
species_richness_list[i] <- lapply(species_richness_list, function(x) species_richness)
}
```

The only thing is I get a warning message saying the number of items to replace is not a multiple of the replacement length, but everything seems to be working
